### ISSUE TITLE
All content vanished after update

### ISSUE THREAD

**Issue by Struppi** [YunoHost-Apps/lionwiki-t2t_ynh#23] opened 2024-02-05 12:17 UTC
I use YunoHost  11.2.9.1 (stable) and now Yunowiki Version: 3.2.12~ynh5

Since my last update all my content of the wiki is gone. I didn't expected this and use a couple of apps in my yunohost, so I can't say it for sure when it happened. I did an greater update last friday but didn't noticed something strange. today I want add some new content  in my wiki but there is only the default lionwiki content. Luckily it's not my main wiki, but could this really happen and how to prevent?

Add: I did this complete update with my Browser at the Yunohost Backend.

**Comment by farvardin** [comment] 2024-02-06 20:30
@Struppi I'm also investigating the recent update changes.
As the wiki is text based, all your content should still be there.

Log with ssh if you can, then cd to /var/www/lionwiki-t2t (if you have several instances of the wiki, it might have several others such as /var/www/lionwiki-t2t__2/ etc)

all pages should be inside /var/www/lionwiki-t2t/var/pages/

it might be the main.txt page has been altered by the update 

What happens if you browse on the wiki the "recent" pages? All the ones in var/pages should be there

you can get it at youryunohostserver.com/lionwiki-t2t/index.php?action=recent

**Comment by Struppi** [comment] 2024-02-06 21:28
yes, I can login via ssh. I have one instance. the main.txt is there but just contain the new content. 
The History (recent changes) shows only changes from the default installation and since the last update. The main site exists only since the update. 

[While I wrote this, there was a new update for Lionwiki]
I just update now and it remove again the content. But something is strange. Before the update the timestamp of most files in /var/www/lionwiki-t2t/var/pages/ was from July 2023, except main.txt was from 5.2.2024 
Now it is all from 2.2.2024

**Comment by farvardin** [comment] 2024-02-06 21:38
@Struppi did you wrote other files beside main.txt?

main.txt shouldn't be modified but if is had been, it should be fixed. Anyway, even if this happened, other txt files shouldn't be removed at all! 

I'm trying to upgrade 2 different instances of this app, on 2 different servers, from  3.2.12~ynh4 à 2024.02.02~ynh1 and it failed in both case so I can't really see what happened...

**Comment by Struppi** [comment] 2024-02-06 22:11
Yes, I createtd some other sites inside the wiki, but they are all gone. I know have "2024.02.02~ynh1"

**Comment by farvardin** [comment] 2024-02-06 22:29
I'm sorry about that. At least there should be an archived with backup before the upgrade inside `` /home/yunohost.backup/archives/`` (it should be named like ``lionwiki-t2t-pre-upgrade2.tar``)

I've checked in my (failed) upgrade, the archive contained .txt files I've created in some of my wikis:

```
apps/lionwiki-t2t/backup/var/www/lionwiki-t2t/var/pages/links.txt                                             
apps/lionwiki-t2t/backup/var/www/lionwiki-t2t/var/pages/mails.txt                                             
apps/lionwiki-t2t/backup/var/www/lionwiki-t2t/var/pages/main.txt                                        
apps/lionwiki-t2t/backup/var/www/lionwiki-t2t/var/pages/office.emails.txt
```

**Comment by Struppi** [comment] 2024-02-06 23:07
It is not important for me - I use the wiki just for sharing some stuff between two computers.

there is a backup file, but it's from before the last of today, but after the content was vanished.

**Comment by farvardin** [comment] 2024-02-07 14:05
I could reproduce this, I've changed the part in my upgrade (color problem) which prevented to continue, and now it's even worse:

- I could reproduce the failing to complete the upgrade
- it didn't manage to automatically restore the app, resulting in an half installation, with all wiki pages replaced by the default ones.
- I've tried to restore from the backup, it complained the /var/www/lionwiki-t2t folder was still present, so I've removed it by ssh and the I could restore everything (all was still there before the upgrade

It looks like there is a problem with the backup script:


```
2024-02-07 14:54:11,091: DEBUG - Could not run script: /var/cache/yunohost/app_tmp_work_dirs/app_ivv80kpf/scripts/backup
```

https://paste.yunohost.org/raw/eqecehehir

**Comment by farvardin** [comment] 2024-02-07 14:15
I've tried another upgrade on the same server (not changing anything from the testing git repo), this time it didn't fail, and could come to completion, however, again it removed all user data from var/pages/ and replaced it by the default ones from the installation.
I managed to uninstall and put the backup online without problem (without data loss)

**Comment by farvardin** [comment] 2024-02-07 15:30
fixed with https://github.com/YunoHost-Apps/lionwiki-t2t_ynh/pull/25

**Comment by Struppi** [comment] 2024-12-12 08:24
YunoHost 11.3.0.2 (stable)
Lionwiki 2024.09.27~ynh1

After this update I did again lost all my data. I did no deeper investigation, just looked in the directory where the data is. It just contain the example files.

**Comment by farvardin** [comment] 2024-12-12 16:47
@Struppi I've fixed it again, it was because of "full_replace" which was added again with this commit: https://github.com/YunoHost-Apps/lionwiki-t2t_ynh/commit/6606b873f0f854542294caae034c1bcfb9256df4#diff-57aeb84da86cb7420dfedd8e49bc644fb799d5413d01927a0417bde753e8922f

you can upgrade with ``sudo yunohost app upgrade lionwiki-t2t -u https://github.com/YunoHost-Apps/lionwiki-t2t_ynh/tree/testing --debug`` meanwhile it's coming from testing into main branch.

**Closed** 2024-12-12 17:47 UTC

**Comment by Struppi** [comment] 2024-12-12 18:12
Thanx.
I don't mind. the wiki isn't the most important app for me. Loosing the data of nextcloud or even more freshRSS, would be a pain. But as I told before the wiki is just a helper between several computer, so I won't try to restore the data.

**Comment by farvardin** [comment] 2024-12-12 18:19
I've put a warning in the code so I hope nobody will add this full_replace again in the future...

**Comment by farvardin** [comment] 2024-12-12 21:19
> Oh, and btw despite this problem it works better than before. At the last version I always got an empty(white) screen after saving a page (my workaround was to recall the start page everytime I saved). This is now as it should be.

@Struppi well, maybe a previous version was set to php8, which is not totally compatible at the moment. I had also the white page problem, and the only workaround was to reload the page after saving. Now it's back to php7.4, which is not a long term solution. In the next release it will be possible to select the version of php (7.4 or 8 and above), and I'll try to find a fix for this empty page error.
